DELETE FROM CUSTOMERS
	WHERE CITY='BOMBAY';

DELETE FROM DEPOSIT
	WHERE AMOUNT<=1000;

DELETE FROM BORROW
	WHERE BNAME='AJNI';

DELETE FROM BORROW
	WHERE LOANNO BETWEEN 201 AND 210;

DELETE FROM DEPOSIT
	WHERE ADATE>'01-DEC-96';

TRUNCATE TABLE CUSTOMERS;

DELETE FROM DEPOSIT
	WHERE CNAME='ANIL' AND ACTNO=101;

DELETE FROM DEPOSIT
	WHERE BNAME!='ANDHERI';

DELETE FROM BORROW
	WHERE AMOUNT<2000 AND BNAME!='VRCE';

DROP TABLE BRANCH;



SELECT * FROM DEPOSIT;

