CREATE TABLE STUDENT_MARKS
(SID INT, SNAME VARCHAR(50), MARKS INT);

INSERT INTO STUDENT_MARKS
VALUES(1,'JOHN',90),(2,'MARTIN',80),(3,'CAROL',89),(4,'JACK',99),(4,'ROSE',88),(5,'MARY',90);

SELECT * FROM STUDENT_MARKS;

SELECT COUNT(SNAME) FROM STUDENT_MARKS;

SELECT SUM(MARKS) FROM STUDENT_MARKS;

SELECT AVG(MARKS) FROM STUDENT_MARKS;

SELECT MIN(MARKS) FROM STUDENT_MARKS;

SELECT MAX(MARKS) FROM STUDENT_MARKS;

