CREATE TABLE EMPLOYEE
(EID INT NOT NULL, ENAME VARCHAR(50) NOT NULL, DEPARTMENT VARCHAR(50) NOT NULL, SALARY DECIMAL(8,2) NOT NULL, JoiningDate DATETIME NOT NULL, CITY VARCHAR(50) NOT NULL);


INSERT INTO EMPLOYEE
VALUES(101,'RAHUL','ADMIN',56000,'1-JAN-90','RAJKOT'),
	  (102,'HARDIK','IT',18000,'25-SEP-90','AHMEDABAD'),
      (103,'BHAVIN','HR',25000,'14-MAY-91','BARODA'),
	  (104,'BHOOMI','ADMIN',39000,'8-FEB-91','RAJKOT'),
	  (105,'ROHIT','IT',17000,'23-JUL-90','JAMNAGAR'),
	  (106,'PRIYA','IT',9000,'18-OCT-90','AHEMDABAD'),
	  (107,'NEHA','HR',34000,'25-DEC-91','RAJKOT');

SELECT * FROM EMPLOYEE;

Select max(salary) as maximum, min(salary) as Minimum, sum(salary) as Total_Sal, avg(salary) as Average_Sal from employee;

SELECT COUNT(EID) FROM EMPLOYEE;

SELECT MAX(SALARY) FROM EMPLOYEE
	WHERE DEPARTMENT='IT';

SELECT COUNT(DISTINCT CITY) FROM EMPLOYEE;

SELECT CITY, COUNT(EID) FROM EMPLOYEE GROUP BY CITY;

UPDATE EMPLOYEE
	SET CITY='AHMEDABAD' 
	WHERE EID=106;

SELECT CITY FROM EMPLOYEE GROUP BY CITY HAVING COUNT(EID)>1;

SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;

SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;

SELECT MIN(SALARY) FROM EMPLOYEE 
	WHERE CITY='AHMEDABAD';

SELECT DEPARTMENT FROM EMPLOYEE 
	WHERE CITY='RAJKOT'
	GROUP BY DEPARTMENT 
	HAVING SUM(SALARY)>50000;

SELECT COUNT(EID) FROM EMPLOYEE WHERE CITY='RAJKOT';

SELECT MAX(SALARY)-MIN(SALARY) AS SAL_DIFFERENCE FROM EMPLOYEE;

SELECT COUNT(EID) FROM EMPLOYEE WHERE JoiningDate<'1-JAN-91';

SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEE
	GROUP BY DEPARTMENT HAVING SUM(SALARY)>35000
	ORDER BY SUM(SALARY);

SELECT DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT HAVING COUNT(EID)>2;

SELECT MIN(SALARY) FROM EMPLOYEE WHERE CITY='RAJKOT';

SELECT CITY, COUNT(EID) FROM EMPLOYEE GROUP BY CITY;

SELECT DEPARTMENT, MIN(SALARY) FROM EMPLOYEE
	GROUP BY DEPARTMENT;

SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY CITY;

SELECT DEPARTMENT, MIN(SALARY) AS 'MIX_SAL',MAX(SALARY) AS 'MAX_SAL',SUM(SALARY) AS 'SUM_SAL' FROM EMPLOYEE
	GROUP BY DEPARTMENT;



	
 







