CREATE TABLE STUDENT
(RNO INT,NAME VARCHAR(50),CITY VARCHAR(50),DID INT);

CREATE TABLE ACADEMIC
(RNO INT,SPI DECIMAL(4,2),BKLOG INT);

CREATE TABLE DEPARTMENT
(DID INT,DNAME VARCHAR(50));

INSERT INTO STUDENT
VALUES (101,'RAJU','RAJKOT',10),
	   (102,'AMIT','AHMEDABAD',20),
	   (103,'SANJAY','BARODA',40),
	   (104,'NEHA','RAJKOT',20),
	   (105,'MEERA','AHMEDABAD',30),
	   (106,'MAHESH','BARODA',10);

INSERT INTO ACADEMIC
VALUES (101,8.8,0),(102,9.2,2),
	   (103,7.5,1),(104,8.2,4),
	   (105,7.0,2),(106,8.9,3);

INSERT INTO DEPARTMENT
VALUES (10,'COMPUTER'),(20,'ELECTRICAL'),
       (30,'MECHANICAL'),(40,'CIVIL');


SELECT RNO,NAME,CITY FROM STUDENT 
	WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');

SELECT NAME FROM STUDENT
	WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE SPI>8);

SELECT RNO,NAME,CITY FROM STUDENT 
	WHERE CITY='RAJKOT'
	AND DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');

SELECT COUNT(*) FROM STUDENT
	WHERE DID=(SELECT DID FROM DEPARTMENT
				WHERE DNAME='ELECTRICAL');

SELECT NAME FROM STUDENT
	WHERE RNO = (SELECT RNO FROM ACADEMIC
					WHERE SPI=(SELECT MAX(SPI) FROM ACADEMIC
									WHERE SPI<(SELECT MAX(SPI) FROM ACADEMIC)));

SELECT * FROM STUDENT
	WHERE RNO IN(SELECT RNO FROM ACADEMIC 
					WHERE BKLOG>1);

SELECT NAME FROM STUDENT
	WHERE DID IN(SELECT DID FROM DEPARTMENT
					WHERE DNAME='COMPUTER'
					   OR DNAME='MECHANICAL');

SELECT NAME FROM STUDENT
	WHERE DID=(SELECT DID FROM STUDENT
				WHERE RNO=102);


SELECT NAME FROM STUDENT
	WHERE RNO=(SELECT RNO FROM ACADEMIC
				WHERE SPI>9)

	AND DID=(SELECT DID FROM DEPARTMENT
				WHERE DNAME='ELECTRICAL');

