CREATE TABLE STUDENT1
(RNO INT,NAME VARCHAR(50),BRANCH VARCHAR(50));

CREATE TABLE RESULT1
(RNO INT, SPL DECIMAL(4,2));

SP_RENAME 'RESULT1.SPL', 'SPI';

CREATE TABLE EMPLOYEE1
(EMPLOYEENO VARCHAR(50), NAME VARCHAR(50), MANAGERNO VARCHAR(50));

INSERT INTO STUDENT1
VALUES (101,'RAJU','CE'),(102,'AMIT','CE'),
	   (103,'SANJAY','ME'),(104,'NEHA','EC'),
	   (105,'MEERA','EE'),(106,'MAHESH','ME');

INSERT INTO RESULT1
VALUES (101,8.8),(102,9.2),(103,7.6),(104,8.2),(105,7.0),(107,8.9);

INSERT INTO EMPLOYEE1
VALUES ('E01','TARUN',NULL),('E02','ROHAN','E02'),
	   ('E03','PRIYA','E01'),('E04','MILAN','E03'),
	   ('E05','JAY','E01'),('E06','ANJANA','E04');

SELECT * FROM STUDENT1;
SELECT * FROM RESULT1;
SELECT * FROM EMPLOYEE1;


SELECT * FROM STUDENT1 CROSS JOIN RESULT1;
--OR
SELECT * FROM STUDENT1,RESULT1;

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM 
	   STUDENT1 S LEFT OUTER JOIN RESULT1 R
	   ON S.RNO=R.RNO
	   WHERE BRANCH='CE';
--OR
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM 
	   STUDENT1 S INNER JOIN RESULT1 R
	   ON S.RNO=R.RNO AND S.BRANCH='CE';

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM 
	   STUDENT1 S LEFT OUTER JOIN RESULT1 R
	   ON S.RNO=R.RNO
	   WHERE S.BRANCH!='EC';

SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT1 S
	   INNER JOIN RESULT1 R
	   ON S.RNO=R.RNO
	   GROUP BY S.BRANCH;

SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT1 S
	   INNER JOIN RESULT1 R
	   ON S.RNO=R.RNO
	   GROUP BY S.BRANCH
	   ORDER BY AVG(R.SPI);

SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT1 S
	   INNER JOIN RESULT1 R
	   ON S.RNO=R.RNO
	   WHERE S.BRANCH IN ('CE','ME')
	   GROUP BY S.BRANCH;
--OR
SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT1 S
	   INNER JOIN RESULT1 R
	   ON S.RNO=R.RNO AND S.BRANCH IN ('CE','ME')
	   GROUP BY S.BRANCH;

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT1 S LEFT OUTER JOIN RESULT1 R
			  ON S.RNO=R.RNO;

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT1 S RIGHT OUTER JOIN RESULT1 R
			  ON S.RNO=R.RNO;

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT1 S FULL OUTER JOIN RESULT1 R
			  ON S.RNO=R.RNO;

SELECT M.NAME AS 'EMPLOYEE',E.NAME AS 'MANAGER' FROM EMPLOYEE1 E INNER JOIN EMPLOYEE1 M
	   ON M.MANAGERNO=E.EMPLOYEENO;








