SELECT LEN(NULL),LEN('HELLO'), LEN('BLANK');
SELECT UPPER('maulik'), LOWER('MAUIK');
SELECT SUBSTRING('MAULIK',1,3);
SELECT SUBSTRING('MAULIK BHATT',3,10);
SELECT REPLACE('aabc123efg','123','XYZ'), 
	   REPLACE('abcabcabc','c',5);
SELECT ASCII('a'),ASCII('A'),ASCII('z'),ASCII('Z'),ASCII('0'),ASCII('9');
SELECT CHAR(97),CHAR(65),CHAR(122),CHAR(90),CHAR(48),CHAR(57);
SELECT TRIM('         HELLO WORLD           ');
SELECT LTRIM('         HELLO WORLD           ');
SELECT RTRIM('         HELLO WORLD           ');
SELECT LEFT('SQL SERVER',4), RIGHT('SQL SERVER',5);
SELECT CAST('1234.56' AS FLOAT);
SELECT CONVERT(FLOAT, 10.58);
SELECT SPACE(10) + 'MAULIK' ;
SELECT 'DARSHAN ' + 'UNIVERSITY';
SELECT CONCAT('DARSHAN ', 'UNIVERSITY');
SELECT REVERSE('DARSHAN');
SELECT REPLICATE('MAULIK ',3);
SELECT STUFF('SQL SERVER',1,3,'HTML');
SELECT COALESCE(NULL,NULL,'SQL',NULL,'CSS');
SELECT ISNUMERIC('25');
SELECT ISNUMERIC(25);
SELECT ISNUMERIC('ABC');
SELECT CHARINDEX('T','CUSTOMER');


