--STORED PROCEDURE
/*
	CREAT PROCEDURE Procudure_Name
	AS
	BEGIN
		QUERY OR STATEMENT 
	END
*/

CREATE TABLE STUDENT2
(RNO INT,NAME VARCHAR(50),BRANCH VARCHAR(50));

CREATE TABLE RESULT
(RNO INT,SPI DECIMAL(4,2));

INSERT INTO STUDENT2
VALUES (101,'RAJU','CE'),
       (102,'AMIT','CE'),
	   (103,'SANJAY','ME'),
	   (104,'NEHA','EC'),
	   (105,'MEERA','EE'),
	   (106,'MAHESH','ME');

SELECT * FROM STUDENT2;

INSERT INTO RESULT 
VALUES (101,8.8),(102,9.2),
       (103,7.6),(104,8.2),
	   (105,7.0),(107,8.9);



CREATE PROCEDURE GetStudentDetail2
AS
BEGIN
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
		FROM STUDENT2 S FULL OUTER JOIN RESULT R
		ON S.RNO=R.RNO;
END

EXEC GetStudentDetail2;

CREATE PROCEDURE GetStudentDetailByRollNo
@Rno int
AS
BEGIN
SELECT * FROM STUDENT2
WHERE Rno=@Rno
END 


EXEC GetStudentDetailByRollNo 101;

CREATE PROCEDURE StudentInsert
@Rno int,
@Name varchar(50),
@Branch varchar(50)
AS 
BEGIN
INSERT INTO STUDENT2
(Rno,Name,Branch)
VALUES
(@Rno,@Name,@Branch)
END 

EXEC StudentInsert 107,'KARAN','CE';
SELECT *FROM STUDENT2;





