CREATE TABLE STUDENT5
(RNO INT ,NAME VARCHAR(50), BRANCH VARCHAR(50));

CREATE TABLE RESULT5
(RNO INT, SPI DECIMAL(4,2), BACKLOG INT);


INSERT INTO RESULT5
VALUES (101,8.5,0),(102,5.4,1),(103,6.1,0),(104,2.5,4),
	   (105,9.0,0),(106,1.1,5);

INSERT INTO STUDENT5
VALUES (101,'RAJU','CE'),(102,'RAJ','ME'),
       (103,'RAM','CE'), (104,'RAJESH','EC'),
	   (105,'SHYAM','ME'),(106,'ROHIT','EL');

DELETE FROM STUDENT5;

--1
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI 
	FROM STUDENT5 S INNER JOIN RESULT5 R
	ON S.RNO=R.RNO
	WHERE BRANCH!='EC';

SELECT AVG(SPI) FROM RESULT5 R INNER JOIN STUDENT5 S
ON S.RNO=R.RNO
WHERE BRANCH='CE' OR BRANCH='ME';

SELECT BRANCH,MAX(SPI) FROM RESULT5 R INNER JOIN STUDENT5 S
ON S.RNO=R.RNO
GROUP BY S.BRANCH
ORDER BY MAX(SPI);

SELECT BRANCH,BACKLOG FROM STUDENT5 S INNER JOIN RESULT5 R
ON S.RNO=R.RNO
WHERE BACKLOG>3;

SELECT NAME FROM STUDENT5 
WHERE RNO LIKE '10%' AND NAME LIKE '____';

SELECT NAME+' HAVING '+CAST(SPI AS VARCHAR(20))+' SPI WITH '+
CAST(BACKLOG AS VARCHAR(20))+' BACKLOGS IN THIS SEMESTER'
FROM STUDENT5 S INNER JOIN RESULT5 R
ON S.RNO=R.RNO;

SELECT S.RNO,NAME,SPI FROM STUDENT5 S INNER JOIN RESULT5 R
ON S.RNO=R.RNO
WHERE R.BACKLOG>1;

SELECT NAME FROM STUDENT5
WHERE BRANCH='EL';

SELECT DISTINCT BRANCH FROM STUDENT;

SELECT TOP 50 PERCENT * FROM RESULT5





	